# -*- coding: utf-8 -*-
"""Kelas Disiplin Oktober.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQZashjYFjS8e-Hdyay3mDFjU0GTCKdb
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

df = pd.read_excel("/content/kelas disiplin oktober.xlsx")
df.head()

df.info()

df['menyalami'].fillna(df['menyalami'].mode()[0], inplace=True)

df["bersih_teras"].str.split(".", expand=True)

def hapus_setelah_titik(str):
    return str.split(".")[0]

for y in range (3, 16):
  df[df.columns[y]] = df[df.columns[y]].apply(hapus_setelah_titik)

df.head()

df["keaktifan"].replace({"1": "25", "2": "50", "3": "75", "4": "100"}, inplace=True)

kolom = ['bersih_teras', 'kerapian', 'kelengkapan', 'sepatu', 'perizinan', 'masuk_kelas', 'tugas', 'respon_sampah', 'respon_papan_tulis', 'respon_meja_kursi', 'membangunkan', 'menyalami']

for x in kolom:
  df[x].replace({"1": "33.333", "2": "66.666", "3": "99.999"}, inplace=True)

df.head()

df.info()

for y in range (3, 16):
  df[df.columns[y]] = df[df.columns[y]].astype(float)

df.head()

df["kelengkapan_total"] = df.iloc[:, 5:7].sum(axis=1)/2
df["keaktifan_total"] = df.iloc[:, 7:11].sum(axis=1)/4
df["respon_total"] = df.iloc[:, 11:16].sum(axis=1)/5

df.head()

df_total = df[["kelas", "bersih_teras", "kerapian", "kelengkapan_total", "keaktifan_total","respon_total"]]
df_total.head()

aggregate = df_total.groupby("kelas").mean()
aggregate["keseluruhan"] = aggregate.mean(axis=1)

aggregate.rename(columns={"bersih_teras": "kebersihan"}, inplace=True)

aggregate.sort_values(by="keseluruhan", ascending=False).round(2)

sns.barplot(data=aggregate['keseluruhan'].sort_values(ascending=False), orient='h')
plt.title('Grafik Lomba Kelas Disiplin Oktober [Keseluruhan]')
plt.xlabel('Rata-Rata Akhir')
plt.ylabel('Kelas');

sns.barplot(data=aggregate['kebersihan'].sort_values(ascending=False), orient='h')
plt.title('Grafik Lomba Kelas Disiplin Agustus [Kelas Ter-Bersih]')
plt.xlabel('Kebersihan')
plt.ylabel('Kelas');

sns.barplot(data=aggregate['kerapian'].sort_values(ascending=False), orient='h')
plt.title('Grafik Lomba Kelas Disiplin Oktober [Kelas Ter-Rapi]')
plt.xlabel('Kerapian')
plt.ylabel('Kelas');

sns.barplot(data=aggregate['keaktifan_total'].sort_values(ascending=False), orient='h')
plt.title('Grafik Lomba Kelas Disiplin Oktober [Kelas Ter-Aktif]')
plt.xlabel('Keaktifan')
plt.ylabel('Kelas');

df['kelas'].value_counts()

